-- Run once against the PostgreSQL/Neon database before deploying the backend.
-- SQLAlchemy persists Python enum member NAMES (e.g. PATIENT_CREATED) for audit_logs.action.
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'STAFF_DEACTIVATED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'PATIENT_DELETED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'ENCOUNTER_COMPLETED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'ENCOUNTER_DELETED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'BACKUP_CREATED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'BACKUP_RESTORED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'REPORT_EXPORTED';
ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'PATIENT_REFERRED';
